name: Deploy contents on AWS
on:
  push:
      branches:
        - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo ${AWS_ACCESS_KEY_ID}
          aws s3 sync --region ap-northeast-1 . s3://aws-handson-edge-delivery-20231214 --debug
